[project]
name = "jarvis-using-python"
version = "0.1.0"
description = "Voice assistant built using Python"
readme = "README.md"
requires-python = ">=3.7"

dependencies = [
    "pyttsx3 == 2.90",
    "SpeechRecognition",
    "pyaudio",
    "wikipedia",
    "pywhatkit",
    "pyautogui",
]
